# Generated by Django 5.2.8 on 2025-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=50)),
                ('employe_id', models.IntegerField()),
                ('employe_salary', models.IntegerField()),
            ],
        ),
    ]
